### ISSUE TITLE
i can not make a copyed slide  with background color 

### ISSUE THREAD

**Issue by easylogic** [zerobased-co/veryslide#4]
i want to add  a slide with previous slide's background-color 

<img width="148" alt="스크린샷 2019-08-30 오전 10 52 20" src="https://user-images.githubusercontent.com/591983/63987723-46419b80-cb14-11e9-8e05-306849cc662c.png">

**Comment by lqez** [comment]
Thank you for using Veryslide. I added a `Duplicate` button.
https://github.com/zerobased-co/veryslide/commit/17404370be6dd8734d6d5a403a7c9d9be54623f1
