### ISSUE TITLE
I can't show my tag string. 

### ISSUE THREAD

**Issue by easylogic** [zerobased-co/veryslide#7]
Previously registered strings in the form of tags become real html tags and can no longer be viewed as strings.

What should I do?

<img width="1042" alt="스크린샷 2019-12-09 오후 6 09 09" src="https://user-images.githubusercontent.com/591983/70422423-127cf700-1aaf-11ea-9aa9-d623b89e7925.png">

**Comment by lqez** [comment]
Could you share your `slideId`? I will check it out.

**Comment by easylogic** [comment]
@lqez  
This is my slide. 

https://veryslide.com/slide/udiC2jOqn54hqpAyZwIY

**Comment by lqez** [comment]
Fixed by https://github.com/zerobased-co/veryslide/commit/8666dfa91174f66091c53e2440d3f80d8d3d0e57
Thanks.
